### ISSUE TITLE
Doesn't seem to work any more

### ISSUE THREAD

**Issue by turkeyphant** [nikersify/alfred-polyglot#6]
Can set default language but in-line translation is broken.

<img width="582" alt="Screenshot 2019-03-20 13 04 34" src="https://user-images.githubusercontent.com/8129583/54686269-ca790700-4b10-11e9-9ec7-52655d3b0ffb.png">

Stack trace:

<img width="1468" alt="Screenshot 2019-03-20 13 04 41" src="https://user-images.githubusercontent.com/8129583/54686268-c8af4380-4b10-11e9-90c7-000a61bd88ef.png">

**Comment by rockymountainhigh1943** [comment]
I am also getting this error and would LOVE to use this workflow. Perhaps there is an API update?

**Comment by nikersify** [comment]
hey, this is most likely happening because of google blocking requests from you for some reason - i've switched the unmaintained translation library to a fresher fork, try installing `1.3.0` to see if it'll fix it.

many people have also experienced this problem, and in all the times i've looked at it i unfortunately wasn't able to come up with any concrete step-by-step solution on how to fix it properly.

i'll keep this issue open till we get some human readable message message in place of this error - perhaps linking to a troubleshooting guide with some workarounds? (would basically be a compiled version of the solutions in [this thread](https://www.alfredforum.com/topic/11235-polyglot-yet-another-google-translate-workflow/). pr's welcome :blush:

**Comment by turkeyphant** [comment]
Not having any other issues with Google Translate on web or via APIs. Only when trying to use this.

**Comment by turkeyphant** [comment]
Okay, had to manually `rm -r` the old version to get it to install with `npm` but `1.3.0` seems to be working now.

Just some odd issues prefixing translations from Spanish to English with "to" for some reason.

<img width="515" alt="Screenshot 2019-05-22 14 42 27" src="https://user-images.githubusercontent.com/8129583/58179638-820ccf80-7ca0-11e9-84d7-a7b00e22dcb6.png">
<img width="589" alt="Screenshot 2019-05-22 14 42 35" src="https://user-images.githubusercontent.com/8129583/58179641-83d69300-7ca0-11e9-9f01-542b7dc0395b.png">
<img width="501" alt="Screenshot 2019-05-22 14 43 39" src="https://user-images.githubusercontent.com/8129583/58179644-8507c000-7ca0-11e9-8f28-127b6e328867.png">
<img width="591" alt="Screenshot 2019-05-22 14 43 45" src="https://user-images.githubusercontent.com/8129583/58179647-8638ed00-7ca0-11e9-8478-af3855219ec3.png">

**Comment by nikersify** [comment]
https://github.com/nikersify/alfred-polyglot/issues/6#issuecomment-494809993 should be fixed in e3199726b9623f9d26d2fc50d124388b71b823a1
